/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package silab.sd.personapp.view.form;

import silab.sd.personapp.view.component.PersonAdd;
import java.awt.BorderLayout;
import silab.sd.personapp.view.component.ConfigurationPerson;

/**
 *
 * @author HP
 */
public class MainFrm extends javax.swing.JDialog {

    /**
     * Creates new form MainFrm
     */
    public MainFrm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBody = new javax.swing.JPanel();
        menu = new javax.swing.JMenuBar();
        mnConfig = new javax.swing.JMenu();
        mnItemPerson = new javax.swing.JMenuItem();
        mnPerson = new javax.swing.JMenu();
        menuItemAddPerson = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout pnlBodyLayout = new javax.swing.GroupLayout(pnlBody);
        pnlBody.setLayout(pnlBodyLayout);
        pnlBodyLayout.setHorizontalGroup(
            pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );
        pnlBodyLayout.setVerticalGroup(
            pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 373, Short.MAX_VALUE)
        );

        mnConfig.setText("Configuration");

        mnItemPerson.setText("Person");
        mnItemPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItemPersonActionPerformed(evt);
            }
        });
        mnConfig.add(mnItemPerson);

        menu.add(mnConfig);

        mnPerson.setText("Person");

        menuItemAddPerson.setText("Add");
        menuItemAddPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAddPersonActionPerformed(evt);
            }
        });
        mnPerson.add(menuItemAddPerson);

        menu.add(mnPerson);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(pnlBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemAddPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAddPersonActionPerformed
          addToBodyPanel(new PersonAdd());
    }//GEN-LAST:event_menuItemAddPersonActionPerformed

    private void mnItemPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItemPersonActionPerformed
        addToBodyPanel(new ConfigurationPerson());
    }//GEN-LAST:event_mnItemPersonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar menu;
    private javax.swing.JMenuItem menuItemAddPerson;
    private javax.swing.JMenu mnConfig;
    private javax.swing.JMenuItem mnItemPerson;
    private javax.swing.JMenu mnPerson;
    private javax.swing.JPanel pnlBody;
    // End of variables declaration//GEN-END:variables


    public void addToBodyPanel(javax.swing.JComponent comp){
       pnlBody.removeAll();
       pnlBody.setLayout(new BorderLayout());
       pnlBody.add(comp, BorderLayout.CENTER);
       comp.setVisible(true);
       pnlBody.revalidate();
    }

}
