/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package silab.sd.personapp.view.component;

import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
import javax.swing.JLabel;
import javax.swing.JRadioButton;

/**
 *
 * @author HP
 */
public class Pick1of2RB extends javax.swing.JPanel implements GetValue {

    /**
     * Creates new form Pick1of2RB
     */
    public Pick1of2RB() {
        initComponents();
        btnGroup.add(rbValue1);
        btnGroup.add(rbValue2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroup = new javax.swing.ButtonGroup();
        rbValue1 = new javax.swing.JRadioButton();
        rbValue2 = new javax.swing.JRadioButton();
        lblText = new javax.swing.JLabel();
        lblError = new javax.swing.JLabel();

        rbValue1.setText("Value1");

        rbValue2.setText("Value2");
        rbValue2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbValue2ActionPerformed(evt);
            }
        });

        lblText.setText("Text:");

        lblError.setForeground(new java.awt.Color(255, 0, 0));
        lblError.setText("errorText");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblText)
                .addGap(79, 79, 79)
                .addComponent(rbValue1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addComponent(rbValue2)
                .addContainerGap(54, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(lblError)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbValue1)
                    .addComponent(rbValue2)
                    .addComponent(lblText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblError)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void rbValue2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbValue2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbValue2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroup;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblText;
    private javax.swing.JRadioButton rbValue1;
    private javax.swing.JRadioButton rbValue2;
    // End of variables declaration//GEN-END:variables

    public JLabel getLblText() {
        return lblText;
    }

    public JLabel getLblError() {
        return lblError;
    }

    public JRadioButton getRbValue2() {
        return rbValue2;
    }

    public JRadioButton getRbValue1() {
        return rbValue1;
    }
    
    
    private boolean isSelected(ButtonGroup buttonGroup) {
        return (buttonGroup.getSelection() != null);
    }
    
    private JRadioButton getSelectedRadioButton(ButtonGroup buttonGroup) {

    Enumeration<AbstractButton> abstractButtons = buttonGroup.getElements();
    JRadioButton radioButton = null;

    while (abstractButtons.hasMoreElements()) {
        radioButton = (JRadioButton) abstractButtons.nextElement();
        if (radioButton.isSelected()) {
            break;
        }
    }
    return radioButton;
}
    
    @Override
    public Object getValue() throws Exception {
        if(!isSelected(btnGroup)){
            lblError.setText("Polje je obavezno");
            throw new Exception("Polje je obavezno");
        }
        return getSelectedRadioButton(btnGroup).getText();
    }
    
    public void setRButtonsText(String value1, String value2){
        rbValue1.setText(value1);
        rbValue2.setText(value2);
    }

    
}
